FROM ubuntu:20.04
WORKDIR /usr/app
COPY . . 

RUN apt-get update && apt-get install -y dos2unix bash
RUN dos2unix s3-init.sh
RUN chmod +x s3-init.sh
RUN chmod 777 mc

CMD ["/bin/bash", "/usr/app/s3-init.sh"]